[tool.poetry]
name = "poetry-sort"
version = "0.0.0"
description = ""
readme = "README.md"
authors = ["celsius narhwal <hello@celsiusnarhwal.dev>"]

[tool.poetry.dependencies]
python = "^3.11"
alianator = "^3.0.0"
poetry = "^1.2"

[tool.poetry.plugins."poetry.application.plugin"]
sort = "poetry_sort.plugin:PoetrySortPlugin"

[build-system]
build-backend = "poetry.core.masonry.api"
requires = ["poetry-core"]
