on:
  release:
    types:
      - published

  workflow_dispatch:


jobs:
  publish:
    name: Publish to PyPI
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Publish With Poetry
        uses: celsiusnarhwal/poetry-publish@v2
        with:
          python-version: 3.11.1
          poetry-version: 1.3.1
          build: true
          token: ${{ secrets.PYPI_TOKEN }}